apiVersion: v1
kind: Pod
metadata:
  name: portfolio-pod
spec:
  containers:
    - name: web
      image: portfolio-web:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx

    - name: log-watcher
      image: busybox:1.36
      command: ["sh", "-c", "tail -F /var/log/nginx/access.log /var/log/nginx/error.log"]
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx

  volumes:
    - name: logs
      emptyDir: {}
